### ISSUE TITLE
ShiftCut...

### ISSUE THREAD

**Issue by Yousefv1** [unanimated/luaegisub#11]
Hi..
I hope you are Fine.

I have 2 Lines sequent, A and B:
(A) ends before 10F from KeyF
(B) begins In The KeyF
So when I wont Snap (A) Line to KeyF with "KeyF snap" on "shiftCut" I added those num: SB"0", EndsBefore"12", SA"0", EA"0" and click"Apply to ALL"; Nothing happened
But when I Selected (A) Line and "Apply to SELECTED"; it's worked!!

So The problem is that (A) Line/s  is unknown in Script until I Find it and Select it.

I use v3.1

**Comment by Yousefv1** [comment]
I Forgot, the "Prevent Overlaps" is enabled

**Comment by unanimated** [comment]
Confirmed.

The overlap check doesn't happen if only 1 line is selected. With all lines, it happens, but I forgot to convert the start of the next line to frame and back to time. This conversion fixes it.

Line 376 in the script:

nextart=nextline.start_time end

should be:

nextart=fr2ms(ms2fr(nextline.start_time)) end

A new release is unlikely to come anytime soon, if ever, so just fix this line yourself if you need it.

**Comment by Yousefv1** [comment]
It works perfectly!
Thank you so much and I wish you well.
