### ISSUE TITLE
About hotkeys feature

### ISSUE THREAD

**Issue by Yousefv1** [unanimated/luaegisub#13]
hi again..
hope you're fine
I have a Noob question about the hotkeys feature
How do I use it? in "shiftcute" exp...

**Comment by unanimated** [comment]
Not sure what you mean. If you mean the general use of hotkeys in Aegisub, you can check this: http://docs.aegisub.org/3.1/Options/#hotkeys

**Comment by Yousefv1** [comment]
Sorry for being late, I was sick since Friday, But thankful to Allah always and forever.

What I mean is that in your guide "http://unanimated.hostfree.pw/ts/scripts-manuals.htm?i=2", you mentioned about the hotkeys.

**Comment by unanimated** [comment]
Well, I don't know what specifically you're asking about, but how to use hotkeys is in that link I gave you.

**Comment by Yousefv1** [comment]
Anyway, thank you.
