### ISSUE TITLE
a slight bug on ShiftCut

### ISSUE THREAD

**Issue by Yousefv1** [unanimated/luaegisub#14]
hello..
I hope you are Fine and healthy.

There is a slight bug on ShiftCut:
a line Start between keyFrames, and Ends after Keyframe with one frame, so when i want snap the End to the KeyFrame nothing work!
-The Time line total is 0.50ms
-The CPS line is 10

on shiftcut v3.1, and CPC is 0.

**Comment by unanimated** [comment]
As far as I can tell from your description, this would happen when the resulting line would be under 450ms. It's not a bug. Lines under 450ms are considered hard to read even if they're short, so they don't snap.
If you want to change this, you can find this line in ShiftCut:
>       if endok and endt-start>450 then line.end_time=endt end
It's line #433 in my current version. You can change the "450" to something smaller if you want.
If this happens with lines that would end up longer than 450ms, then the problem would be something else and I'd need more information to determine what. Probably it's this, though.

**Comment by Yousefv1** [comment]
It works!
Thank you so much.
