### ISSUE TITLE
shiftcut: problem in Mark changed lines!

### ISSUE THREAD

**Issue by Yousefv1** [unanimated/luaegisub#7]
Hello!
Thanks for the creativity and beauty offered by your project.
I found a problem In "shiftcut" but it is really annoying
Which is When I check on "Mark changed lines", and apply "Link lines"; All lines in selected styles, become Market as [linked], Both changing and unchanged lines!!! Then I can't check the changes.
I hope the problem is clear

**Comment by unanimated** [comment]
Right. It's actually been fixed, but I've never released the fix, along with a few other scripts. I'll try to release the batch over the weekend.

**Comment by Yousefv1** [comment]
Thank you very much, I'll be waiting for that then.
and I hope you keep updating your creative project; It is indescribably useful.
